### PR TITLE
Adding gfftranslator.py

### PR DESCRIPTION
**Pull request by puja-trivedi**

### CODE REVIEW

**Comment by djarecka** [comment]
@puja-trivedi - I think you mentioned that the model should be also slightly changed for this to work, could you please add the changes.

Also, can you provide an example how to use it (where to get data from)

**Comment by puja-trivedi** [comment]
Changes that were implemented: 
- Changed type of in_taxon in GeneAnnotation from str -> OrganismTaxon in kbmodel
- Moved gfftranslator.py to 'scripts' directory 
- Added README.md to 'scripts' directory that explains how to use gfftranslator.py

Not Implemented:
- When I took a second look at the serialize function in gfftranslator.py, I realized it is not as general as I though. It is written to specifically serialize AnnotationCollection.annotations. Given that information, should I still separate out that function and add it to utils?

**Comment by djarecka** [comment]
I think the serialize function could be changed to more general, but we can wait until we have another example that would need a similar function to do it.

Could you please remove `__pycache__` directory, and perhaps add a `.gitignore` file that would ignore these directories in the future, example could be found [here](https://github.com/nipype/pydra/blob/426564eca3efa7d840fdca33bdbef6a1c88e2ffc/.gitignore#L5)

**Comment by puja-trivedi** [comment]
Removed __pycache__ directory

**Pull request merged**
